Update azure-pipelines.yml for Azure Pipelines
Adding Connectivity Check Script

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -17,6 +17,17 @@ steps:
     echo Add other tasks to build, test, and deploy your project.
     echo See https://aka.ms/yaml
   displayName: 'Run a multi-line script'
+
+- script: echo "Starting connectivity test to Fortify URLs"
+  displayName: 'Start Connectivity Check'
+
+- script: |
+    echo "Pinging Fortify SSC URL..."
+    curl -I https://ssc.aat.deloitte.com/ssc || echo "Connection to SSC failed."
+
+    echo "Pinging Fortify Scan Central URL..."
+    curl -I https://sast.aat.deloitte.com/scancentral-ctrl || echo "Connection to ScanCentral failed."
+  displayName: 'Connectivity Test to Fortify SSC and Scan Central'
   
 - task: FortifyScanCentralSAST@7
   inputs:
