Update azure-pipelines.yml for Azure Pipelines
Adding ping

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -10,6 +10,14 @@ pool:
   name: AAT-Pool
 
 steps:
+- script: |
+    echo "Pinging Fortify SSC URL..."
+    ping -c 4 ssc.aat.deloitte.com || echo "Unable to reach Fortify SSC URL"
+    
+    echo "Pinging Fortify Scan Central URL..."
+    ping -c 4 sast.aat.deloitte.com/scancentral-ctrl || echo "Unable to reach Fortify Scan Central URL"
+  displayName: 'Ping Fortify SSC and Scan Central URLs'
+
 - script: echo Hello, world!
   displayName: 'Run a one-line script'
 
